MTDSA-9064 Play 28 Upgrades, Dependencies and Plugins
hmrc/mtd-savings-accounts pull request #65
Opened 2021-06-24 13:22 UTC by ngangaNjiraini

2021-06-24 14:42 UTC, james-work-account requested changes

2021-06-24 14:42 UTC, james-work-account commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.2","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/home/nganga/Documents/idea-IC-193.6494.35/jbr/bin/java","-Xms100m","-Xmx100m","-classpath","/home/nganga/.IdeaI
remove

2021-06-24 14:42 UTC, james-work-account commented on app/v2/connectors/DesConnector.scala
> +      createSavingsAccountRequestData.createSavingsAccount)(writes, reads[CreateSavingsAccountResponse], desHeaderCarrier(), implicitly)
needs content-type additional header

2021-06-24 14:42 UTC, james-work-account commented on app/v2/connectors/DesConnector.scala
> +      DesSavingsInterestAnnualIncome.writes, reads[DesAmendSavingsAccountAnnualSummaryResponse], desHeaderCarrier(), implicitly)
needs content-type additional header

2021-06-24 14:42 UTC, james-work-account commented on project/plugins.sbt
> +//resolvers += Resolver.url("hmrc-sbt-plugin-releases", url("https://dl.bintray.com/hmrc/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
don't forget to remove these

2021-06-28 07:59 UTC, DreamcastKnight commented on project/AppDependencies.scala
> +    "org.scalatest"          %% "scalatest"          % "3.2.3"             % scope,
scalatest can be 3.2.9

2021-06-28 07:59 UTC, DreamcastKnight commented on project/AppDependencies.scala
> +    "org.scalatestplus.play" %% "scalatestplus-play" % "3.1.3"             % scope,
can be 5.1.0 looking at other deppendency prs

2021-06-29 09:37 UTC, DreamcastKnight approved these changes

2021-06-29 09:39 UTC, merged